var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/orders/track/[track]/route.js")
R.c("server/chunks/[root-of-the-server]__03f9abe0._.js")
R.c("server/chunks/node_modules_next_d739b5ba._.js")
R.c("server/chunks/src_lib_s3_ts_ee3926b3._.js")
R.c("server/chunks/[root-of-the-server]__c0cfec52._.js")
R.c("server/chunks/[root-of-the-server]__73cd6d4d._.js")
R.c("server/chunks/_ad0988f1._.js")
R.m(588355)
R.m(78335)
module.exports=R.m(78335).exports
