var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/free-events/[id]/route.js")
R.c("server/chunks/[root-of-the-server]__3a467fd3._.js")
R.c("server/chunks/node_modules_next_d739b5ba._.js")
R.c("server/chunks/src_lib_outlook_ts_0cc6f615._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_fa90cebf.js")
R.c("server/chunks/[root-of-the-server]__c0cfec52._.js")
R.c("server/chunks/_ad0988f1._.js")
R.m(594076)
R.m(992006)
module.exports=R.m(992006).exports
