var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/orders/route.js")
R.c("server/chunks/[root-of-the-server]__d0581bc6._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_62a22a1c.js")
R.c("server/chunks/node_modules_next_d739b5ba._.js")
R.c("server/chunks/src_lib_fortnox_ts_8e4dde45._.js")
R.c("server/chunks/src_lib_s3_ts_ee3926b3._.js")
R.c("server/chunks/[root-of-the-server]__568e2b1a._.js")
R.c("server/chunks/_ad0988f1._.js")
R.c("server/chunks/[root-of-the-server]__c0cfec52._.js")
R.c("server/chunks/src_lib_outlook_ts_0cc6f615._.js")
R.m(670902)
R.m(536883)
module.exports=R.m(536883).exports
