var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/fortnox/supplier-invoices/route.js")
R.c("server/chunks/[root-of-the-server]__192ed84a._.js")
R.c("server/chunks/src_lib_s3_ts_ee3926b3._.js")
R.c("server/chunks/src_lib_fortnox_ts_8e4dde45._.js")
R.c("server/chunks/[root-of-the-server]__c0cfec52._.js")
R.c("server/chunks/_ad0988f1._.js")
R.c("server/chunks/node_modules_next_d739b5ba._.js")
R.m(803219)
R.m(524501)
module.exports=R.m(524501).exports
