var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/fortnox/articles/route.js")
R.c("server/chunks/[root-of-the-server]__652c81c0._.js")
R.c("server/chunks/node_modules_next_d739b5ba._.js")
R.c("server/chunks/src_lib_fortnox_ts_8e4dde45._.js")
R.c("server/chunks/[root-of-the-server]__c0cfec52._.js")
R.c("server/chunks/_ad0988f1._.js")
R.c("server/chunks/src_lib_s3_ts_ee3926b3._.js")
R.m(448000)
R.m(178562)
module.exports=R.m(178562).exports
