// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/403" | "/[marketing]" | "/account" | "/admin/business-hours" | "/articles" | "/articles/[articleNumber]" | "/articles/new" | "/calendar-old/[track]" | "/calendar/[track]" | "/calendar2" | "/component-lab" | "/cookies" | "/customers" | "/customers/new" | "/dashboard" | "/home" | "/integritet" | "/login" | "/orders/[id]" | "/orders/[id]/fakturerad" | "/orders/[id]/track/[track]" | "/orders/archived" | "/orders/completed" | "/orders/new" | "/orders/new2_0" | "/orders/overview" | "/orders/track/[track]" | "/personal-calendar" | "/quotes/new" | "/quotes/new2.0" | "/sakerhet" | "/shimmer-demo" | "/snake" | "/supplier-invoices" | "/test" | "/villkor"
type AppRouteHandlerRoutes = "/api/account/fortnox/connection" | "/api/account/mfa/totp" | "/api/account/outlook/calendars" | "/api/account/outlook/connection" | "/api/account/outlook/notifications" | "/api/account/outlook/oauth/callback" | "/api/account/outlook/oauth/start" | "/api/account/outlook/sync" | "/api/account/profile-image" | "/api/account/push-subscriptions" | "/api/auth/[...nextauth]" | "/api/auth/mfa-status" | "/api/calendar" | "/api/calendar/[id]" | "/api/calendar/[id]/label" | "/api/calendar/[id]/status" | "/api/calendar/business-hours" | "/api/calendar/conflicts" | "/api/calendar/create-with-resolution" | "/api/command-search" | "/api/customer-references" | "/api/customer-references/[id]" | "/api/fortnox/accounts" | "/api/fortnox/articles" | "/api/fortnox/articles/[articleNumber]" | "/api/fortnox/costcenters" | "/api/fortnox/customers" | "/api/fortnox/fortnox-test" | "/api/fortnox/oauth/callback" | "/api/fortnox/oauth/start" | "/api/fortnox/offers" | "/api/fortnox/orders" | "/api/fortnox/pricelists" | "/api/fortnox/supplier-invoices" | "/api/fortnox/suppliers" | "/api/free-events" | "/api/free-events/[id]" | "/api/notifications" | "/api/orders" | "/api/orders/[id]" | "/api/orders/[id]/files" | "/api/orders/[id]/files/[fileId]" | "/api/orders/[id]/files/[fileId]/renew" | "/api/orders/[id]/fortnox-debug" | "/api/orders/[id]/fortnox-sync" | "/api/orders/[id]/tracks/[track]/status" | "/api/orders/[id]/tracks/[track]/time" | "/api/orders/archived" | "/api/orders/completed" | "/api/orders/confirm-billing" | "/api/orders/recent" | "/api/orders/summary" | "/api/orders/track/[track]" | "/api/personal-calendar" | "/api/profile-images/[userId]" | "/api/register" | "/api/stored-files/[encodedKey]" | "/api/tips" | "/api/users"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = "/orders/new2.0"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[marketing]": { "marketing": string; }
  "/403": {}
  "/account": {}
  "/admin/business-hours": {}
  "/api/account/fortnox/connection": {}
  "/api/account/mfa/totp": {}
  "/api/account/outlook/calendars": {}
  "/api/account/outlook/connection": {}
  "/api/account/outlook/notifications": {}
  "/api/account/outlook/oauth/callback": {}
  "/api/account/outlook/oauth/start": {}
  "/api/account/outlook/sync": {}
  "/api/account/profile-image": {}
  "/api/account/push-subscriptions": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/auth/mfa-status": {}
  "/api/calendar": {}
  "/api/calendar/[id]": { "id": string; }
  "/api/calendar/[id]/label": { "id": string; }
  "/api/calendar/[id]/status": { "id": string; }
  "/api/calendar/business-hours": {}
  "/api/calendar/conflicts": {}
  "/api/calendar/create-with-resolution": {}
  "/api/command-search": {}
  "/api/customer-references": {}
  "/api/customer-references/[id]": { "id": string; }
  "/api/fortnox/accounts": {}
  "/api/fortnox/articles": {}
  "/api/fortnox/articles/[articleNumber]": { "articleNumber": string; }
  "/api/fortnox/costcenters": {}
  "/api/fortnox/customers": {}
  "/api/fortnox/fortnox-test": {}
  "/api/fortnox/oauth/callback": {}
  "/api/fortnox/oauth/start": {}
  "/api/fortnox/offers": {}
  "/api/fortnox/orders": {}
  "/api/fortnox/pricelists": {}
  "/api/fortnox/supplier-invoices": {}
  "/api/fortnox/suppliers": {}
  "/api/free-events": {}
  "/api/free-events/[id]": { "id": string; }
  "/api/notifications": {}
  "/api/orders": {}
  "/api/orders/[id]": { "id": string; }
  "/api/orders/[id]/files": { "id": string; }
  "/api/orders/[id]/files/[fileId]": { "id": string; "fileId": string; }
  "/api/orders/[id]/files/[fileId]/renew": { "id": string; "fileId": string; }
  "/api/orders/[id]/fortnox-debug": { "id": string; }
  "/api/orders/[id]/fortnox-sync": { "id": string; }
  "/api/orders/[id]/tracks/[track]/status": { "id": string; "track": string; }
  "/api/orders/[id]/tracks/[track]/time": { "id": string; "track": string; }
  "/api/orders/archived": {}
  "/api/orders/completed": {}
  "/api/orders/confirm-billing": {}
  "/api/orders/recent": {}
  "/api/orders/summary": {}
  "/api/orders/track/[track]": { "track": string; }
  "/api/personal-calendar": {}
  "/api/profile-images/[userId]": { "userId": string; }
  "/api/register": {}
  "/api/stored-files/[encodedKey]": { "encodedKey": string; }
  "/api/tips": {}
  "/api/users": {}
  "/articles": {}
  "/articles/[articleNumber]": { "articleNumber": string; }
  "/articles/new": {}
  "/calendar-old/[track]": { "track": string; }
  "/calendar/[track]": { "track": string; }
  "/calendar2": {}
  "/component-lab": {}
  "/cookies": {}
  "/customers": {}
  "/customers/new": {}
  "/dashboard": {}
  "/home": {}
  "/integritet": {}
  "/login": {}
  "/orders/[id]": { "id": string; }
  "/orders/[id]/fakturerad": { "id": string; }
  "/orders/[id]/track/[track]": { "id": string; "track": string; }
  "/orders/archived": {}
  "/orders/completed": {}
  "/orders/new": {}
  "/orders/new2_0": {}
  "/orders/new2.0": {}
  "/orders/overview": {}
  "/orders/track/[track]": { "track": string; }
  "/personal-calendar": {}
  "/quotes/new": {}
  "/quotes/new2.0": {}
  "/sakerhet": {}
  "/shimmer-demo": {}
  "/snake": {}
  "/supplier-invoices": {}
  "/test": {}
  "/villkor": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
