// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(marketing)/[marketing]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[marketing]">> = Specific
  const handler = {} as typeof import("../../src/app/(marketing)/[marketing]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/403/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/403">> = Specific
  const handler = {} as typeof import("../../src/app/403/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account">> = Specific
  const handler = {} as typeof import("../../src/app/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/business-hours/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/business-hours">> = Specific
  const handler = {} as typeof import("../../src/app/admin/business-hours/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/articles/[articleNumber]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/articles/[articleNumber]">> = Specific
  const handler = {} as typeof import("../../src/app/articles/[articleNumber]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/articles/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/articles/new">> = Specific
  const handler = {} as typeof import("../../src/app/articles/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/articles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/articles">> = Specific
  const handler = {} as typeof import("../../src/app/articles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/calendar-old/[track]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/calendar-old/[track]">> = Specific
  const handler = {} as typeof import("../../src/app/calendar-old/[track]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/calendar/[track]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/calendar/[track]">> = Specific
  const handler = {} as typeof import("../../src/app/calendar/[track]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/calendar2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/calendar2">> = Specific
  const handler = {} as typeof import("../../src/app/calendar2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/component-lab/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/component-lab">> = Specific
  const handler = {} as typeof import("../../src/app/component-lab/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/cookies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cookies">> = Specific
  const handler = {} as typeof import("../../src/app/cookies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customers/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customers/new">> = Specific
  const handler = {} as typeof import("../../src/app/customers/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customers">> = Specific
  const handler = {} as typeof import("../../src/app/customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/home/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/home">> = Specific
  const handler = {} as typeof import("../../src/app/home/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/integritet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/integritet">> = Specific
  const handler = {} as typeof import("../../src/app/integritet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/orders/[id]/fakturerad/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/[id]/fakturerad">> = Specific
  const handler = {} as typeof import("../../src/app/orders/[id]/fakturerad/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/orders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/orders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/orders/[id]/track/[track]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/[id]/track/[track]">> = Specific
  const handler = {} as typeof import("../../src/app/orders/[id]/track/[track]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/orders/archived/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/archived">> = Specific
  const handler = {} as typeof import("../../src/app/orders/archived/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/orders/completed/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/completed">> = Specific
  const handler = {} as typeof import("../../src/app/orders/completed/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/orders/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/new">> = Specific
  const handler = {} as typeof import("../../src/app/orders/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/orders/new2_0/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/new2_0">> = Specific
  const handler = {} as typeof import("../../src/app/orders/new2_0/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/orders/overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/overview">> = Specific
  const handler = {} as typeof import("../../src/app/orders/overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/orders/track/[track]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/track/[track]">> = Specific
  const handler = {} as typeof import("../../src/app/orders/track/[track]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/personal-calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/personal-calendar">> = Specific
  const handler = {} as typeof import("../../src/app/personal-calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/quotes/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/quotes/new">> = Specific
  const handler = {} as typeof import("../../src/app/quotes/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/quotes/new2.0/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/quotes/new2.0">> = Specific
  const handler = {} as typeof import("../../src/app/quotes/new2.0/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sakerhet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sakerhet">> = Specific
  const handler = {} as typeof import("../../src/app/sakerhet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/shimmer-demo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shimmer-demo">> = Specific
  const handler = {} as typeof import("../../src/app/shimmer-demo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/snake/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/snake">> = Specific
  const handler = {} as typeof import("../../src/app/snake/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/supplier-invoices/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/supplier-invoices">> = Specific
  const handler = {} as typeof import("../../src/app/supplier-invoices/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/test/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test">> = Specific
  const handler = {} as typeof import("../../src/app/test/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/villkor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/villkor">> = Specific
  const handler = {} as typeof import("../../src/app/villkor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/account/fortnox/connection/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/fortnox/connection">> = Specific
  const handler = {} as typeof import("../../src/app/api/account/fortnox/connection/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/account/mfa/totp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/mfa/totp">> = Specific
  const handler = {} as typeof import("../../src/app/api/account/mfa/totp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/account/outlook/calendars/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/outlook/calendars">> = Specific
  const handler = {} as typeof import("../../src/app/api/account/outlook/calendars/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/account/outlook/connection/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/outlook/connection">> = Specific
  const handler = {} as typeof import("../../src/app/api/account/outlook/connection/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/account/outlook/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/outlook/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/api/account/outlook/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/account/outlook/oauth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/outlook/oauth/callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/account/outlook/oauth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/account/outlook/oauth/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/outlook/oauth/start">> = Specific
  const handler = {} as typeof import("../../src/app/api/account/outlook/oauth/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/account/outlook/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/outlook/sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/account/outlook/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/account/profile-image/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/profile-image">> = Specific
  const handler = {} as typeof import("../../src/app/api/account/profile-image/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/account/push-subscriptions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/push-subscriptions">> = Specific
  const handler = {} as typeof import("../../src/app/api/account/push-subscriptions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/mfa-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/mfa-status">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/mfa-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/calendar/[id]/label/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calendar/[id]/label">> = Specific
  const handler = {} as typeof import("../../src/app/api/calendar/[id]/label/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/calendar/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calendar/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/calendar/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/calendar/[id]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calendar/[id]/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/calendar/[id]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/calendar/business-hours/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calendar/business-hours">> = Specific
  const handler = {} as typeof import("../../src/app/api/calendar/business-hours/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/calendar/conflicts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calendar/conflicts">> = Specific
  const handler = {} as typeof import("../../src/app/api/calendar/conflicts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/calendar/create-with-resolution/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calendar/create-with-resolution">> = Specific
  const handler = {} as typeof import("../../src/app/api/calendar/create-with-resolution/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/calendar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calendar">> = Specific
  const handler = {} as typeof import("../../src/app/api/calendar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/command-search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/command-search">> = Specific
  const handler = {} as typeof import("../../src/app/api/command-search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customer-references/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customer-references/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/customer-references/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/customer-references/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customer-references">> = Specific
  const handler = {} as typeof import("../../src/app/api/customer-references/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/fortnox/accounts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fortnox/accounts">> = Specific
  const handler = {} as typeof import("../../src/app/api/fortnox/accounts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/fortnox/articles/[articleNumber]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fortnox/articles/[articleNumber]">> = Specific
  const handler = {} as typeof import("../../src/app/api/fortnox/articles/[articleNumber]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/fortnox/articles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fortnox/articles">> = Specific
  const handler = {} as typeof import("../../src/app/api/fortnox/articles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/fortnox/costcenters/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fortnox/costcenters">> = Specific
  const handler = {} as typeof import("../../src/app/api/fortnox/costcenters/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/fortnox/customers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fortnox/customers">> = Specific
  const handler = {} as typeof import("../../src/app/api/fortnox/customers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/fortnox/fortnox-test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fortnox/fortnox-test">> = Specific
  const handler = {} as typeof import("../../src/app/api/fortnox/fortnox-test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/fortnox/oauth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fortnox/oauth/callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/fortnox/oauth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/fortnox/oauth/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fortnox/oauth/start">> = Specific
  const handler = {} as typeof import("../../src/app/api/fortnox/oauth/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/fortnox/offers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fortnox/offers">> = Specific
  const handler = {} as typeof import("../../src/app/api/fortnox/offers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/fortnox/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fortnox/orders">> = Specific
  const handler = {} as typeof import("../../src/app/api/fortnox/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/fortnox/pricelists/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fortnox/pricelists">> = Specific
  const handler = {} as typeof import("../../src/app/api/fortnox/pricelists/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/fortnox/supplier-invoices/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fortnox/supplier-invoices">> = Specific
  const handler = {} as typeof import("../../src/app/api/fortnox/supplier-invoices/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/fortnox/suppliers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fortnox/suppliers">> = Specific
  const handler = {} as typeof import("../../src/app/api/fortnox/suppliers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/free-events/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/free-events/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/free-events/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/free-events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/free-events">> = Specific
  const handler = {} as typeof import("../../src/app/api/free-events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orders/[id]/files/[fileId]/renew/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[id]/files/[fileId]/renew">> = Specific
  const handler = {} as typeof import("../../src/app/api/orders/[id]/files/[fileId]/renew/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orders/[id]/files/[fileId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[id]/files/[fileId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/orders/[id]/files/[fileId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orders/[id]/files/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[id]/files">> = Specific
  const handler = {} as typeof import("../../src/app/api/orders/[id]/files/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orders/[id]/fortnox-debug/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[id]/fortnox-debug">> = Specific
  const handler = {} as typeof import("../../src/app/api/orders/[id]/fortnox-debug/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orders/[id]/fortnox-sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[id]/fortnox-sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/orders/[id]/fortnox-sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orders/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/orders/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orders/[id]/tracks/[track]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[id]/tracks/[track]/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/orders/[id]/tracks/[track]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orders/[id]/tracks/[track]/time/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[id]/tracks/[track]/time">> = Specific
  const handler = {} as typeof import("../../src/app/api/orders/[id]/tracks/[track]/time/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orders/archived/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/archived">> = Specific
  const handler = {} as typeof import("../../src/app/api/orders/archived/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orders/completed/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/completed">> = Specific
  const handler = {} as typeof import("../../src/app/api/orders/completed/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orders/confirm-billing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/confirm-billing">> = Specific
  const handler = {} as typeof import("../../src/app/api/orders/confirm-billing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orders/recent/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/recent">> = Specific
  const handler = {} as typeof import("../../src/app/api/orders/recent/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders">> = Specific
  const handler = {} as typeof import("../../src/app/api/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orders/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/summary">> = Specific
  const handler = {} as typeof import("../../src/app/api/orders/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orders/track/[track]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/track/[track]">> = Specific
  const handler = {} as typeof import("../../src/app/api/orders/track/[track]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/personal-calendar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/personal-calendar">> = Specific
  const handler = {} as typeof import("../../src/app/api/personal-calendar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/profile-images/[userId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profile-images/[userId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/profile-images/[userId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/register">> = Specific
  const handler = {} as typeof import("../../src/app/api/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/stored-files/[encodedKey]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stored-files/[encodedKey]">> = Specific
  const handler = {} as typeof import("../../src/app/api/stored-files/[encodedKey]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tips/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tips">> = Specific
  const handler = {} as typeof import("../../src/app/api/tips/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users">> = Specific
  const handler = {} as typeof import("../../src/app/api/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
