var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/orders/[id]/route.js")
R.c("server/chunks/[root-of-the-server]__d807e6f0._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_6f0878e7.js")
R.c("server/chunks/src_lib_fortnox_ts_8e4dde45._.js")
R.c("server/chunks/src_lib_s3_ts_ee3926b3._.js")
R.c("server/chunks/node_modules_next_d739b5ba._.js")
R.c("server/chunks/[root-of-the-server]__c0cfec52._.js")
R.c("server/chunks/_ad0988f1._.js")
R.c("server/chunks/[root-of-the-server]__73cd6d4d._.js")
R.m(234686)
R.m(49295)
module.exports=R.m(49295).exports
