var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/free-events/route.js")
R.c("server/chunks/[root-of-the-server]__0a1ae277._.js")
R.c("server/chunks/node_modules_next_d739b5ba._.js")
R.c("server/chunks/src_lib_outlook_ts_0cc6f615._.js")
R.c("server/chunks/_ad0988f1._.js")
R.c("server/chunks/[root-of-the-server]__c0cfec52._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_fa90cebf.js")
R.m(645878)
R.m(567042)
module.exports=R.m(567042).exports
